### PR TITLE
[concept] Constructors, `this` pointer

### PR DESCRIPTION
**Pull request by nikiljos**
### Concepts covered
- `this` Pointer
- Constructors and Destructors

### CODE REVIEW

**Comment by nikiljos** [comment]
### Walkthrough Video
https://www.loom.com/share/d8cb56c6d2a74f12891eb62943d35007

**Comment by Tharun-kailash** [comment]
Hey Nikhil,
It's not mandatory to explicitly declare the destructor but is is actually a good practice in projects.
Your code is good and the explanation provided is clear.

You can go ahead and merge this PR!

**Comment by nikiljos** [comment]
Hi @Tharun-kailash 
Thank you for the review. This PR has been submitted under 2 topics in livebooks, but [one of them](https://kalvium.community/livebooks/oops/OOP_Proj/OOP_Project_constructors_destructors) is pending evaluation. Could you please look into it...

**Comment by Tharun-kailash** [comment]
Hey Nikhil,
It will be updated once evaluations for this pointer are done for all submissions. 
Thanks.

**Pull request merged**
